title: DARE Labs
author: Detroit Action Research Lab
email: ajitsurfs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  We work on projects for improving the human condition using technology and positive intent.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
